<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
            [
                'title' => 'Annual Sports Day',
                'description' => 'Annual sports competition featuring various athletic events for all students.',
                'event_date' => Carbon::now()->addDays(15),
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'location' => 'School Ground',
                'event_type' => 'sports',
                'priority' => 'high',
                'is_all_day' => false,
                'is_active' => true,
                'color' => '#ffc107',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Parent-Teacher Meeting',
                'description' => 'Quarterly meeting to discuss student progress with parents.',
                'event_date' => Carbon::now()->addDays(7),
                'start_time' => '14:00:00',
                'end_time' => '16:00:00',
                'location' => 'Main Auditorium',
                'event_type' => 'meeting',
                'priority' => 'medium',
                'is_all_day' => false,
                'is_active' => true,
                'color' => '#6c757d',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Science Fair',
                'description' => 'Annual science exhibition showcasing student projects and innovations.',
                'event_date' => Carbon::now()->addDays(25),
                'start_time' => '10:00:00',
                'end_time' => '15:00:00',
                'location' => 'Science Building',
                'event_type' => 'academic',
                'priority' => 'high',
                'is_all_day' => false,
                'is_active' => true,
                'color' => '#007bff',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cultural Festival',
                'description' => 'Annual cultural celebration with music, dance, and drama performances.',
                'event_date' => Carbon::now()->addDays(30),
                'start_time' => '18:00:00',
                'end_time' => '22:00:00',
                'location' => 'Open Air Theater',
                'event_type' => 'cultural',
                'priority' => 'medium',
                'is_all_day' => false,
                'is_active' => true,
                'color' => '#17a2b8',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Student Council Elections',
                'description' => 'Annual elections for student council positions.',
                'event_date' => Carbon::now()->addDays(5),
                'start_time' => '08:00:00',
                'end_time' => '16:00:00',
                'location' => 'Main Building',
                'event_type' => 'other',
                'priority' => 'high',
                'is_all_day' => true,
                'is_active' => true,
                'color' => '#343a40',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Graduation Ceremony',
                'description' => 'Annual graduation ceremony for graduating students.',
                'event_date' => Carbon::now()->addDays(60),
                'start_time' => '15:00:00',
                'end_time' => '18:00:00',
                'location' => 'Main Auditorium',
                'event_type' => 'academic',
                'priority' => 'high',
                'is_all_day' => false,
                'is_active' => true,
                'color' => '#007bff',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Library Week',
                'description' => 'Week-long celebration of reading and library activities.',
                'event_date' => Carbon::now()->addDays(10),
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'location' => 'Library',
                'event_type' => 'academic',
                'priority' => 'low',
                'is_all_day' => true,
                'is_active' => true,
                'color' => '#007bff',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Staff Meeting',
                'description' => 'Monthly staff meeting to discuss school matters.',
                'event_date' => Carbon::now()->addDays(3),
                'start_time' => '15:30:00',
                'end_time' => '16:30:00',
                'location' => 'Conference Room',
                'event_type' => 'meeting',
                'priority' => 'medium',
                'is_all_day' => false,
                'is_active' => true,
                'color' => '#6c757d',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'School Picnic',
                'description' => 'Annual school picnic for students and staff.',
                'event_date' => Carbon::now()->addDays(45),
                'start_time' => '08:00:00',
                'end_time' => '18:00:00',
                'location' => 'City Park',
                'event_type' => 'social',
                'priority' => 'medium',
                'is_all_day' => true,
                'is_active' => true,
                'color' => '#28a745',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Math Olympiad',
                'description' => 'Annual mathematics competition for students.',
                'event_date' => Carbon::now()->addDays(20),
                'start_time' => '10:00:00',
                'end_time' => '12:00:00',
                'location' => 'Classroom 101',
                'event_type' => 'academic',
                'priority' => 'medium',
                'is_all_day' => false,
                'is_active' => true,
                'color' => '#007bff',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('events')->insert($events);
    }
}
